### PR TITLE
Code climate: fix existing Ruff issues

### PR DESCRIPTION
**Pull request by stanislaw**
The next steps: gradually introduce the Ruff config, activate more checks.

### CODE REVIEW

**Comment by stanislaw** [comment]
Let's get to see the CI running this one.

**Comment by stanislaw** [comment]
Let me know when you activated the CI, I could force-push this branch then.

**Comment by kamui-fin** [comment]
I can't seem to find a place to activate that workflow. This is what shows up if I click the "Actions" tab:
image

**Comment by stanislaw** [comment]
This is strange. I took a working file from my project.

**Comment by stanislaw** [comment]
There was an invisible space at the end of the yml file which I have fixed. But the jobs are still not starting anyhow. Can we merge this one with a fix just in case? I will open another one to debug.

**Comment by kamui-fin** [comment]
Maybe the github actions file isn't valid?

**Comment by stanislaw** [comment]
> Maybe the github actions file isn't valid?

I double-checked two times. Looks good to my eyes.

**Comment by kamui-fin** [comment]
@stanislaw Ah wait a minute, it just worked.

**Pull request merged**
