### PR TITLE
Code climate: replace the config dictionary with a dedicated class GenerateVideoTask

### PR DESCRIPTION
**Pull request by stanislaw**
This is a pure refactoring work that transforms dictionary data into dedicated class data. No behavior is changed but only how the data is stored.

This increases the readability and maintainability of the data.

### CODE REVIEW

**Comment by kamui-fin** [comment]
Could we make use of [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) here? It automatically generates `__init__` as well as `__repr__` (for debugging), and could help us trim more code down.

**Comment by kamui-fin** [comment]
I was also wondering if it would be good idea to extract the validation + error handling logic out into these data classes, and simply just have one call per model that would propagate up to `self.error()`.

**Comment by stanislaw** [comment]
> Could we make use of [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) here? It automatically generates `__init__` as well as `__repr__` (for debugging), and could help us trim more code down.

How about we change this later because it might break the compatibility with my subsequent commits? It will be trivial to move from the custom classes to the dataclasses after the main part of my changes is merged. What do you think?

**Comment by kamui-fin** [comment]
> > Could we make use of [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) here? It automatically generates `__init__` as well as `__repr__` (for debugging), and could help us trim more code down.
> 
> How about we change this later because it might break the compatibility with my subsequent commits? It will be trivial to move from the custom classes to the dataclasses after the main part of my changes is merged. What do you think?

Yep, that works.

**Pull request merged**
